services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
