volumes:
  pgdata:
  nodemodules:
  n8n-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      n8n:
        condition: service_started

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      PGPORT: 5432
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 20

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
    volumes:
      - n8n-data:/home/node/.n8n     
    restart: unless-stopped

    
